<a href="https://colab.research.google.com/github/Gavinkim/tensorflow-fashion-mnist-tutorial/blob/master/fashion_mnist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import matplotlib.pyplot as plt

(train_images,train_labels),(test_images,test_labels) = tf.keras.datasets.fashion_mnist.load_data()
train_images.shape

4423680/4422102 [==============================] - 0s 0us/step


(60000, 28, 28)

In [0]:
train_images[0].shape

(28, 28)

In [0]:
train_labels[0].shape

()

In [0]:
test_images.shape

(10000, 28, 28)

In [0]:
test_labels.shape

(10000,)

In [0]:
import numpy as np

np.set_printoptions(linewidth=200)

In [0]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,  13,  73,   0,   0,   1,   4,   0,   0,   0,   0,   1,   1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,   0,  36, 136, 127,  62,  54,   0,   0,   0,   1,   3,   4,   0,   0,   3],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   6,   0, 102, 204, 176, 134, 144, 123,  23,   0,   0,   0,   0,  12,  10,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 155, 236, 207, 178, 107, 156

In [0]:
train_labels[0]

9

In [0]:
class_names = ['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Angle_boot']

In [0]:
class_names[train_labels[0]]

'Angle_boot'

In [0]:
train_images = train_images/255.0
test_images=test_images/255.0

In [0]:
np.round(train_images[0],2)

array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.29, 0.  , 0.  , 0.  , 0.02, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.01, 0.  , 0.14, 0.53, 0.5 , 0.24, 0.21, 0.  , 0.  , 0.  , 0.  , 0.01, 0.02, 0.  , 0.  , 0.01],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.02, 0.  , 0.4 , 0.8 , 0.69, 0.53,

In [0]:
model = tf.keras.Sequential([
  tf.keras.layers.Flatten(input_shape=(28,28)),
  tf.keras.layers.Dense(128,activation='relu'),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dense(128,activation='relu'),
  tf.keras.layers.Dense(64, activation='relu'),
  # tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10,activation='softmax')
])

In [0]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_7 (Dense)              (None, 128)               100480    
_________________________________________________________________
dense_8 (Dense)              (None, 256)               33024     
_________________________________________________________________
dense_9 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_10 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_11 (Dense)             (None, 10)                650       
Total params: 175,306
Trainable params: 175,306
Non-trainable params: 0
________________________________________________

In [0]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['acc'])

In [0]:
model.fit(train_images,train_labels,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4946 - acc: 0.8203
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3708 - acc: 0.8639
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3381 - acc: 0.8742
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3111 - acc: 0.8846
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2916 - acc: 0.8913
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2820 - acc: 0.8935
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2671 - acc: 0.8992
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2560 - acc: 0.9034
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2461 - acc: 0.9072
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2394 - acc: 0.9099


In [0]:
test_loss,test_acc = model.evaluate(test_images,test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.3718 - acc: 0.8767


In [0]:
test_loss, test_acc

(0.3349195420742035, 0.887499988079071)

In [0]:
img = test_images[32]
label = test_labels[32]

In [0]:
img.shape

(28, 28)

In [0]:
img = np.expand_dims(img,0)

In [0]:
img.shape

(1, 28, 28)

In [0]:
test_images.shape

(10000, 28, 28)

In [0]:
predictions = model.predict(img)

In [0]:
predictions

array([[1.5576767e-03, 1.0238194e-01, 1.6284559e-04, 8.9237142e-01, 9.0041431e-04, 3.2168958e-07, 1.5881545e-03, 1.2256714e-06, 1.0360015e-03, 6.5621130e-08]], dtype=float32)

In [0]:
np.argmax(predictions)

3

In [0]:
label

3

In [0]:
class_names[np.argmax(predictions)]

'Dress'